# Generated by Django 2.1.3 on 2018-11-10 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_trade_fk_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='fk_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
