# Generated by Django 2.1.3 on 2018-11-10 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20181109_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='fk_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.Profile'),
        ),
    ]
