# Generated by Django 2.1.3 on 2018-11-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20181110_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whats',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
