# Generated by Django 2.1.3 on 2018-11-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_profile_whats'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='condition',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='interest',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='interestimg',
            field=models.ImageField(blank=True, null=True, upload_to='trades'),
        ),
    ]
