# Generated by Django 2.1.3 on 2018-11-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_auto_20181110_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='description',
            field=models.CharField(max_length=1200),
        ),
    ]
