# Generated by Django 2.1.3 on 2018-11-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_auto_20181110_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='interestdetails',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='description',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
