# Generated by Django 2.1.3 on 2018-11-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_auto_20181110_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='whats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
