# Generated by Django 2.1.3 on 2018-11-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_auto_20181111_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
