# Generated by Django 2.1.3 on 2018-11-11 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_auto_20181111_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='subinterst',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='fk_profile',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.Profile'),
        ),
    ]
