# Generated by Django 2.1.3 on 2018-11-12 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_auto_20181111_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='subinterst',
            new_name='subinterest',
        ),
    ]
